name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-server python3-pip
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Redis master server
      run: |
        sudo rm -rf /var/lib/redis/*  # Clear existing data to avoid compatibility issues
        sudo redis-server --port 6379 --daemonize yes
        sleep 5  # Ensure master server has time to start

    - name: Verify Redis master server
      run: redis-cli -p 6379 ping

    - name: Start Redis replica server
      run: |
        echo 'port 6380' > replica.conf
        echo 'replicaof 127.0.0.1 6379' >> replica.conf
        cat replica.conf  # Log the configuration for verification
        sudo rm -rf /var/lib/redis/*  # Clear existing data to avoid compatibility issues
        sudo redis-server replica.conf --daemonize yes
        sleep 15  # Ensure replica has enough time to start

    - name: Verify Redis replica server
      run: redis-cli -p 6380 ping

    - name: Output Redis logs for master
      run: sudo cat /var/log/redis/redis-server.log

    - name: Output Redis logs for replica
      run: sudo cat /var/log/redis/redis-server.log  

    - name: Run tests
      env:
        REDIS_SERVER_PATH: "/usr/bin/redis-server"
        REDIS_CLI_PATH: "/usr/bin/redis-cli"
        REDIS_BENCHMARK_PATH: "/usr/bin/redis-benchmark"
      run: |
        source venv/bin/activate
        pytest test_redis_bdd.py
