name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Redis
      run: sudo apt-get install -y redis-server

    - name: Start Redis master server
      run: sudo redis-server --port 6379 --daemonize yes

    - name: Verify Redis master server
      run: redis-cli -p 6379 ping

    - name: Start Redis replica server
      run: |
        echo 'port 6380' > replica.conf
        echo 'replicaof 127.0.0.1 6379' >> replica.conf
        sudo redis-server replica.conf --daemonize yes
        sleep 15  # Ensure replica has enough time to start

    - name: Verify Redis replica server
      run: redis-cli -p 6380 ping

    - name: Output Redis logs
      run: sudo tail -n 100 /var/log/redis/redis-server.log

    - name: Run tests
      env:
        REDIS_SERVER_PATH: "/usr/bin/redis-server"
        REDIS_CLI_PATH: "/usr/bin/redis-cli"
        REDIS_BENCHMARK_PATH: "/usr/bin/redis-benchmark"
      run: |
        source venv/bin/activate
        pytest test_redis_bdd.py
