name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Redis
      run: sudo apt-get install -y redis-server

    - name: Start Redis server
      run: sudo systemctl start redis-server

    - name: Verify Redis CLI Path
      run: which redis-cli

    - name: Run tests
      env:
        REDIS_SERVER_PATH: "/usr/bin/redis-server"
        REDIS_CLI_PATH: "/usr/bin/redis-cli"
        REDIS_BENCHMARK_PATH: "/usr/bin/redis-benchmark"
      run: pytest test_redis_bdd.py
